### ISSUE TITLE
Challenge 9: Safe abstractions for `core::time::Duration`

### ISSUE THREAD

**Issue by feliperodri** [model-checking/verify-rust-std#72]
[Challenge 9: Safe abstractions for core::time::Duration](https://model-checking.github.io/verify-rust-std/challenges/0009-duration.html#challenge-9-safe-abstractions-for-coretimeduration)

**Comment by sgpthomas** [comment]
I'm working on this challenge. Will keep you updated on any progress I make.

**Comment by tautschnig** [comment]
@sgpthomas With #136 about to be merged, could you please create a separate PR closing this challenge, akin to #206? Thank you!
